apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: java-mysql
data:
  DB_HOST: "mysql-service" # Kubernetes DNS resolves mysql-service to the right pod automatically.
  DB_PORT: "3306"
  DB_NAME: "team_app"

