apiVersion: v1
kind: Service
metadata:
  name: mysql-service   # SAME AS HOST_NAME POINTS TO
  namespace: java-mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None       # headless - fine for a single stateful pod